[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "authorai"
authors = [{name = "AuthorAI.org", email = "authorai.org@gmail.com"}]
dynamic = ["version", "description"]